build: false

environment:
    matrix:
        - PYTHON: "C:\\Python37"
        - PYTHON: "C:\\Python38"
        - PYTHON: "C:\\Python37-x64"
        - PYTHON: "C:\\Python38-x64"

init:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

install:
    - python -m pip install -r requirements_test.txt
    - python -m pip install -r requirements.txt

test_script:
#    - python -m pytest
    -   ps: |
            cd ..
    -   ps: |
            &$env:PYTHON\python -m pytest
