language: python

os:
    - linux

python:
    - "3.7"

install:
    - pip install -r requirements_test.txt
    - pip install -r requirements.txt


# command to run tests
script:
    - pytest --cov

after_success: coveralls