language: python
sudo: false
dist: xenial

os:
    - linux


cache: pip

python:
    - "3.7"


matrix:
    include:  # Workaround for python 3.7.
        - python: "3.7"
          dist: xenial
          sudo: required

    fast_finish: true


install:
    - pip install -r requirements_test.txt
    - pip install -r requirements.txt


# command to run tests
script:
    - pytest --cov

after_success: coveralls